---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by D.
--- DateTime: 2023/7/15 17:51
---
-- 1.参数列表
-- 1.1.优惠券id
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]
-- 1.3.订单id
local orderId = ARGV[3]

-- 2.数据key
-- 2.1.库存key
local stockKey='seckill:stock:'..voucherId
-- 2.2.订单key
local orderKey='seckill:order:'..voucherId

-- 3.脚本业务
-- 3.1.判断是否有库存 get stockKey
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.1.1.没有库存，直接返回1
    return 1
end
-- 3.2.有库存，判断是否重复下单 SISMEMBER orderKey userId
if (redis.call('SISMEMBER', orderKey, userId) == 1) then
    -- 3.2.1.重复下单，直接返回2
    return 2
end
-- 3.3.没有重复下单，扣减库存 decrby stockKey 1
redis.call('decrby', stockKey, 1)
-- 3.4.记录订单 sadd orderKey userId
redis.call('sadd', orderKey, userId)
-- 3.5.发送消息到队列，XADD stream.order * k1 v1 k2 v2 ...
redis.call('XADD', 'stream.order', '*', 'voucherId', voucherId, 'userId', userId, 'id', orderId);
return 0
